"""Multi-node (SLURM) sharding for very large inputs.

Single-node runs already stream in bounded memory (see ``annotate.mapper``). For
cluster scale we split the input once into N shards, annotate each shard as an
independent SLURM array task, then concatenate the per-shard AIRR TSVs:

    arda split  big.fastq work/shards --shards 50
    # SLURM array task i:
    arda annotate -i work/shards/shard_<i>.fasta -o work/out/out_<i>.tsv ...
    arda merge  work/out  big.airr.tsv

``arda slurm`` writes (and optionally submits) a single ``submit.sh`` that chains
all three with SLURM job dependencies — see ``render_submit_script``.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from .annotate import io as seqio

__all__ = ["split", "merge", "render_submit_script", "SHARD_GLOB"]

SHARD_GLOB = "shard_*.fasta"


def split(input: str | Path, out_dir: str | Path, shards: int,
          *, prefix: str = "shard") -> list[Path]:
    """Round-robin split a FASTA/FASTQ into ``shards`` FASTA files (one pass).

    Round-robin (record ``k`` → shard ``k % shards``) balances load even when
    record sizes vary, and every record lands in exactly one shard.
    """
    if shards < 1:
        raise ValueError("shards must be >= 1")
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = [out_dir / f"{prefix}_{i}.fasta" for i in range(shards)]
    handles = [open(p, "w") for p in paths]
    try:
        for k, (sid, seq) in enumerate(seqio.read_sequences(input)):
            handles[k % shards].write(f">{sid}\n{seq}\n")
    finally:
        for h in handles:
            h.close()
    return paths


def merge(shard_outputs: str | Path | list[Path], output: str | Path) -> Path:
    """Concatenate per-shard AIRR TSVs into one, keeping a single header.

    ``shard_outputs`` may be a directory (its ``*.tsv`` are merged in sorted
    order) or an explicit list of files.
    """
    output = Path(output)
    if isinstance(shard_outputs, (str, Path)) and Path(shard_outputs).is_dir():
        files = sorted(Path(shard_outputs).glob("*.tsv"))
    else:
        files = [Path(p) for p in shard_outputs]  # type: ignore[union-attr]
    if not files:
        raise FileNotFoundError("no shard outputs to merge")
    with open(output, "w") as out:
        for i, p in enumerate(files):
            with open(p) as fh:
                header = fh.readline()
                if i == 0:
                    out.write(header)
                shutil.copyfileobj(fh, out)
    return output


def render_submit_script(
    input: str | Path,
    output: str | Path,
    work_dir: str | Path,
    *,
    shards: int,
    organism: str = "human",
    seqtype: str = "nt",
    threads: int = 8,
    strand: str = "both",
    map_d: bool = True,
    partition: str | None = None,
    time: str = "04:00:00",
    mem: str = "8G",
    arda_mmseqs: str | None = None,
) -> str:
    """Render a ``submit.sh`` that chains split → array-annotate → merge on SLURM.

    Uses ``sbatch --array`` with ``--wrap`` and an ``afterok`` dependency so the
    merge runs only once every shard succeeds. ``arda_mmseqs`` (if given) is
    exported so array tasks find the binary.
    """
    input, output, work_dir = Path(input), Path(output), Path(work_dir)
    shards_dir = work_dir / "shards"
    out_dir = work_dir / "out"
    last = shards - 1
    sbatch_common = [f"--cpus-per-task={threads}", f"--time={time}", f"--mem={mem}"]
    if partition:
        sbatch_common.append(f"--partition={partition}")
    common = " ".join(sbatch_common)
    map_d_flag = "--map-d" if map_d else "--no-map-d"
    env_line = f'export ARDA_MMSEQS="{arda_mmseqs}"' if arda_mmseqs else "# ARDA_MMSEQS from environment"
    return f"""#!/usr/bin/env bash
# Generated by `arda slurm`. Annotate {input} across {shards} SLURM array tasks.
set -euo pipefail
{env_line}

mkdir -p "{shards_dir}" "{out_dir}"

# 1. Split once (cheap, single pass).
arda split "{input}" "{shards_dir}" --shards {shards}

# 2. Annotate each shard as an array task.
ARRAY_JID=$(sbatch --parsable {common} --job-name=arda-map --array=0-{last} \\
  --output="{out_dir}/slurm-%A_%a.log" \\
  --wrap 'arda annotate -i "{shards_dir}/shard_${{SLURM_ARRAY_TASK_ID}}.fasta" \\
          -o "{out_dir}/out_${{SLURM_ARRAY_TASK_ID}}.tsv" \\
          --organism {organism} --seqtype {seqtype} --threads {threads} \\
          --strand {strand} {map_d_flag}')

# 3. Merge once all shards succeed.
sbatch {common} --job-name=arda-merge --dependency=afterok:$ARRAY_JID \\
  --output="{out_dir}/slurm-merge.log" \\
  --wrap 'arda merge "{out_dir}" "{output}"'
"""
