"""A generated script names the arda it was generated BY, not the compute node's PATH.

`ARDA_MMSEQS` has been pinned since the Nextflow module silently built a different aligner. arda
itself was the one tool in a generated script still left to PATH — and on a real cluster that cost
a whole run: `arda cluster submit-samples` mapped every read group successfully and the reduce
array then died with `No such option: --ec-mode`, because the workers resolved `arda` to 2.19.0.
The map flags happened to exist in that version; the reduce flag did not. A sheet's worth of
Stage-1 AIRR, no clonotypes, and an error naming a flag rather than a version.
"""

from __future__ import annotations

import re
import shutil
import subprocess

import pytest

from arda import cluster

RENDERERS = ("render_submit_script", "render_rnaseq_submit_script", "render_samples_submit_script")


def _scripts(tmp_path):
    """One rendered script per renderer, keyed by name."""
    rg = tmp_path / "readgroups.tsv"
    rg.write_text("sample\tread_group\tr1\tr2\tpart_airr\tpart_report\n"
                  "S\t0\t/d/a_1.fq\t/d/a_2.fq\t/w/S/shard_00000.airr.tsv\t/w/S/shard_00000.map.json\n")
    sm = tmp_path / "samples.tsv"
    sm.write_text("sample\tshard_dir\tout_prefix\nS\t/w/S\tS\n")
    return {
        "render_submit_script": cluster.render_submit_script(
            "big.fastq", "out.airr.tsv", tmp_path / "work", shards=4),
        "render_rnaseq_submit_script": cluster.render_rnaseq_submit_script(
            "r1.fq", "S", tmp_path / "work", shards=4, r2="r2.fq"),
        "render_samples_submit_script": cluster.render_samples_submit_script(
            rg, sm, n_read_groups=1, n_samples=1),
    }


def test_arda_binary_is_absolute():
    """A relative path in a generated script depends on the worker's working directory."""
    binary = cluster.arda_binary()
    assert binary.startswith("/"), binary


def test_arda_binary_does_not_resolve_symlinks(tmp_path, monkeypatch):
    """An HPC module points a stable name at the current build; following it pins the wrong one."""
    real = tmp_path / "arda-2.23.0"
    real.write_text("#!/bin/sh\n")
    real.chmod(0o755)
    link = tmp_path / "bin" / "arda"
    link.parent.mkdir()
    link.symlink_to(real)
    monkeypatch.setenv("PATH", str(link.parent))
    assert cluster.arda_binary() == str(link)


@pytest.mark.parametrize("name", RENDERERS)
def test_every_generated_script_exports_and_uses_the_pinned_binary(tmp_path, name):
    script = _scripts(tmp_path)[name]
    assert re.search(r'^export ARDA="/.+"$', script, re.M), "the binary must be exported, absolute"
    # Every arda subcommand goes through it. `\barda ` would also match the `ARDA=` line and the
    # prose, so match a command position: start of a line, or right after `--wrap '`, or after the
    # `; \` continuations the array bodies use.
    bare = re.findall(r"(?:^|--wrap '|; +|^ +)arda (?:map|annotate|cluster) ", script, re.M)
    assert not bare, f"{name} still calls arda through PATH: {bare}"
    assert '"$ARDA" ' in script


@pytest.mark.parametrize("name", RENDERERS)
def test_every_generated_script_is_valid_bash(tmp_path, name):
    """`--wrap '...'` bodies are quoted by hand; a stray quote is a syntax error, not a typo."""
    bash = shutil.which("bash")
    if bash is None:                                     # pragma: no cover - bash is everywhere
        pytest.skip("no bash")
    path = tmp_path / f"{name}.sh"
    path.write_text(_scripts(tmp_path)[name])
    subprocess.run([bash, "-n", str(path)], check=True)


def test_an_explicit_binary_overrides_the_resolved_one(tmp_path):
    script = cluster.render_rnaseq_submit_script(
        "r1.fq", "S", tmp_path / "work", shards=2, arda_bin="/opt/arda/2.23.0/bin/arda")
    assert 'export ARDA="/opt/arda/2.23.0/bin/arda"' in script
